package com.co.castor.modelo;
// Generated 27/10/2022 02:12:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cargos generated by hbm2java
 */
public class Cargos  implements java.io.Serializable {


     private int idcargo;
     private String nombre;
     private Set<Empleados> empleadoses = new HashSet<Empleados>(0);

    public Cargos() {
    }

	
    public Cargos(int idcargo, String nombre) {
        this.idcargo = idcargo;
        this.nombre = nombre;
    }
    public Cargos(int idcargo, String nombre, Set<Empleados> empleadoses) {
       this.idcargo = idcargo;
       this.nombre = nombre;
       this.empleadoses = empleadoses;
    }
   
    public int getIdcargo() {
        return this.idcargo;
    }
    
    public void setIdcargo(int idcargo) {
        this.idcargo = idcargo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Empleados> getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set<Empleados> empleadoses) {
        this.empleadoses = empleadoses;
    }




}


