package com.co.castor.modelo;
// Generated 27/10/2022 02:12:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private long id;
     private Cargos cargos;
     private int cedula;
     private String nombre;
     private String foto;
     private Date fechaIngreso;

    public Empleados() {
    }

	
    public Empleados(long id, Cargos cargos, int cedula, String nombre) {
        this.id = id;
        this.cargos = cargos;
        this.cedula = cedula;
        this.nombre = nombre;
    }
    public Empleados(long id, Cargos cargos, int cedula, String nombre, String foto, Date fechaIngreso) {
       this.id = id;
       this.cargos = cargos;
       this.cedula = cedula;
       this.nombre = nombre;
       this.foto = foto;
       this.fechaIngreso = fechaIngreso;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Cargos getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Cargos cargos) {
        this.cargos = cargos;
    }
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }




}


